name: pbi-milestone
on:
  pull_request:
    types: [opened, edited]

jobs:
  pbi-milestone:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.milestone == null
    steps:
      - name: set milestone
        run: |
          ruby -r json -r shellwords -r uri -e '
            description = "${{ github.event.pull_request.body }}"
            matched = /## PBI Issue\s+- #{URI.regexp}/.match(description)

            return if matched.nil?

            issue_path = matched[7]
            issue = JSON.parse(`curl -H "authorization: Bearer ${{ secrets.PAT }}" \
            "https://api.github.com/repos#{issue_path}"`)

            if issue["labels"].any?{|label| label["name"] == "PBI" } && !issue["milestone"].empty?
              milestones = JSON.parse(`curl -X GET -H "authorization: Bearer ${{ github.token }}" \
              "https://api.github.com/repos/${{ github.repository }}/milestones?state=open"`)

              milestone = milestones.detect{|m| m["title"] == issue["milestone"]["title"]} # 同じタイトルのmilestoneを取得
              params = {milestone: milestone["number"]}
              `curl -X PATCH -H "authorization: Bearer ${{ github.token }}" \
              -d #{Shellwords.escape(params.to_json)} \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}"`
            end
          '
